services:
  backend:
    build:
      context: ./backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"