services:
  backend:
    build:
      context: ./backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:5173"