services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules