services:
  backend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes: [] # Added to ensure no volume mounts

  frontend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - "80:80"  # Override port mapping as we use Nginx for production
    volumes: []  # Added to ensure no volume mounts 
